artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion  
  local_data_file: artifacts/data_ingestion/raw.csv


data_transformation:
  root_dir: artifacts/data_transformation
  train_test_split: artifacts/train_test_split
  raw_file_path: artifacts/data_ingestion/raw.csv
  local_data_file: artifacts/data_transformation/insurance.csv
  train_path: artifacts/train_test_split/train.csv
  test_path: artifacts/train_test_split/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/train_test_split/train.csv
  test_data_path: artifacts/train_test_split/test.csv

model_evaluation:
  root_dir: artifacts/model_evaluation  
  test_data_path: artifacts/train_test_split/test.csv
  metric_file_name: artifacts/model_evaluation/metrics.json
  model_paths:
    LinearRegression: artifacts/model_trainer/linear_regression_model.joblib
    DecisionTree: artifacts/model_trainer/decision_tree_model.joblib
    GradientBoosting: artifacts/model_trainer/gradient_boosting_model.joblib
    XGBoost: artifacts/model_trainer/xgboost_model.joblib
    Ridge: artifacts/model_trainer/ridge_model.joblib
    Lasso: artifacts/model_trainer/lasso_model.joblib
    ElasticNet: artifacts/model_trainer/elasticnet_model.joblib

model_prediction:
  root_dir: artifacts/model_prediction
    
    
