artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion  
  local_data_file: artifacts/data_ingestion/raw.csv

data_validation:
  root_dir: artifacts/data_validation

data_transformation:
  root_dir: artifacts/data_transformation

model_trainer:
  root_dir: artifacts/model_trainer

model_evaluation:
  root_dir: artifacts/model_evaluation  